### ISSUE TITLE
Using in a Saas project - MIT Licence

### ISSUE THREAD

**Issue by joshsny** [rosman83/madyan#1]
Hi there,

Nice work on the template so far, just git cloned it and it looks really good!

I'm interested in using your template in a project for my startup, but can't open source our code.

Is there any chance you are happy to change from a AGPL-3.0 License to an MIT Licence?

**Comment by rosman83** [comment]
Sure - going to go ahead and change the license to MIT

**Comment by rosman83** [comment]
#2
